### ISSUE TITLE
Make the date dynamic

### ISSUE THREAD

**Issue by nyugoh** [nyugoh/todo-pwa#1]
The day and time is static on the home page. Use Javascript to make it dynamic, use Moment.js lib.

**Comment by schezfaz** [comment]
hey @nyugoh! Could I work on this issue?

**Comment by nyugoh** [comment]
Sure, work on it, your are welcome to contribute.

**Comment by schezfaz** [comment]
Thankyou! Working on it!

**Comment by schezfaz** [comment]
Hey I have submitted a Pull Request that tackles this issue!

**Comment by nyugoh** [comment]
Let me review it.

**Comment by nyugoh** [comment]
@schezfaz Thanks for contributing to this project, I have reviewed the code and refactored it. I have moved all the code from dynamicDate.js to main.js.
Otherwise thanks and you'r welcome to join us, we are working on the app every Friday, it's a project to learn how to build Progressive Web Apps(PWA).

**Comment by schezfaz** [comment]
Thankyou! Surely, looking forward to making more contributions!
